# Generated by Django 4.1.13 on 2024-05-27 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0002_embedding_search_vector'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='embedding',
            unique_together=set(),
        ),
    ]
