# Generated by Django 4.1.13 on 2024-06-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0003_alter_embedding_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embedding',
            name='search_vector',
            field=models.TextField(default='', verbose_name='分词'),
        ),
    ]
