# Generated by Django 4.1.13 on 2024-06-28 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('embedding', '0004_alter_embedding_search_vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embedding',
            name='search_vector',
        ),
    ]
